### ISSUE TITLE
Release a new version with nan 2 dependency for Node.js 4.0.0 compatibility.

### ISSUE THREAD

**Issue by ChALkeR** [mscdex/node-mariasql#103]
This is actually not fixed yet, because no release has been made since landing #100.

Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by wzrdtales** [comment]
@mscdex When are you going to release the new version and what is actually blocking it?

**Comment by mscdex** [comment]
I'm currently working on finishing the rewrite, writing tests for it, and then merging into master.

**Comment by wzrdtales** [comment]
@mscdex Alright, thank you for the update!

**Comment by mscdex** [comment]
The fix is now in v0.1.24.

**Comment by wzrdtales** [comment]
@mscdex Doesn't seem to work actually there are still build errors https://travis-ci.org/wzrdtales/node-ultimate-migrate/jobs/80397583#L247

**Comment by blah238** [comment]
@wzrdtales @mscdex Same here: https://travis-ci.org/tgriesser/knex/jobs/81842000#L236

**Comment by mscdex** [comment]
I just merged the rewrite into master. This will not be an issue in the next version (0.2.0).
