### ISSUE TITLE
mariasql crashes on disconnect while disposing of the object

### ISSUE THREAD

**Issue by wzrdtales** [mscdex/node-mariasql#104]
I've run into the following issue.

If the connection was lost and I remove all references to the old connection, node will crash and throw:

    node: ../deps/uv/src/unix/core.c:841: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

Here is a test scenario to reproduce this error yourself.

Steps, get the gist:
1. https://gist.github.com/wzrdtales/3f2b1ee877d689f3916b
2. install mariasql module
3. start the test
4. restart your mariadb database while running the test

I haven't had the time yet to further debug this and look to have a deeper look into this over the next days/weeks. It seems however to be related to an issue with poll_fd, there have occured similar errors in the past in libuv:

https://github.com/JuliaLang/julia/issues/7840

Thus the failure has to be something with uv_poll_t.

**Comment by wzrdtales** [comment]
An additional note, this does only happen if you have more than one instance of mariasql!

**Comment by wzrdtales** [comment]
@mscdex An additional note, this does only happen if you have more than one instance of mariasql!

**Comment by mscdex** [comment]
Well, the good news is this doesn't happen with the rewrite (although your code did expose a different issue there), which is where I'm spending my effort at this point. I am hoping to merge the rewrite branch soon.

**Comment by mscdex** [comment]
v0.2.0 is released now, which should not have the described issue.

**Comment by wzrdtales** [comment]
@mscdex I will start to migrate everything and also several projects of mine, let's see if this even archives some performance improvements :)

**Comment by wzrdtales** [comment]
@mscdex Btw. good to see you've finally a CI running :)

**Comment by wzrdtales** [comment]
@mscdex Do we have an auto reconnect now? And do you have plans or a roadmap until you consider this module as stable (v1.x.x)?

**Comment by mscdex** [comment]
There is no auto reconnect, as I'm not sure there's a good "one size fits all" way to do it.

**Comment by mscdex** [comment]
As far as versioning goes, `mariasql` doesn't use semver, but 0.1.x and 0.2.x are considered "stable."

**Comment by wzrdtales** [comment]
@mscdex Ok, good to know.
And bout the auto reconnect, in your old readme you've had a note about it not being included, thus I just wanted to know if it is now available or not.
