### ISSUE TITLE
npm install (nodejs 4.1.1) errors, cannot find config.gypi

### ISSUE THREAD

**Issue by Leonidaz** [mscdex/node-mariasql#105]
gyp: deps/libmariadbclient/config/config.gypi not found (cwd: /Users/myname/local_dev/bfmweb/server/node_modules/mariasql) while reading includes of binding.gyp while trying to load binding.gyp

i checked what npm downloads and it just excludes config.gypi from the package, really strange....

**Comment by Leonidaz** [comment]
ok, yes, it just doesn't like the name... i renamed the file and references to it and it started to work.  This is the name of the file that npm automatically generated and there was a security flaw and they just decided to probably remove all files with this name from the package..... :)

**Comment by mscdex** [comment]
Duplicate of #102.
