### ISSUE TITLE
Error when installing from npm on nodejs 4

### ISSUE THREAD

**Issue by hectorluis-collado** [mscdex/node-mariasql#106]
I can't install mariasql from npm on nodejs 4.0

**Comment by gitawego** [comment]
same here...

**Comment by mscdex** [comment]
A new version is coming soon.

**Comment by capaj** [comment]
@mscdex is there an estimate on the release of that new version compatible with 4.x.x node?

**Comment by mscdex** [comment]
v0.2.0 is released now and should be fully compatible from node v0.10 through node v4 (as of this writing).

**Comment by blah238** [comment]
@mscdex Is there something we need to change in Travis to get it building there? https://travis-ci.org/tgriesser/knex/jobs/82507781

**Comment by capaj** [comment]
@mscdex works on my Debian 8, but still failing on my windows 8 machine.

**Comment by wzrdtales** [comment]
@mscdex The build is still failing on travis, even with 0.2.0:

https://travis-ci.org/wzrdtales/node-ultimate-migrate/jobs/82530620#L302

**Comment by wzrdtales** [comment]
@mscdex After adding gcc 4.8 to the build environment it works now, but this should really be mentioned within the README.

**Comment by wzrdtales** [comment]
@mscdex It would also make sense to place an install script that verifies needed dependencies such as gcc 4.8, as this breaks the user experience. If a user installs a module which has your module as submodule, this causes much more trouble as if the user gets a message that he needs to install gcc 4.8

**Comment by mscdex** [comment]
@wzrdtales gcc/g++ 4.8 is a requirement of node v4, not `mariasql`. This requirement is listed in the node readme [here](https://github.com/nodejs/node#unix--macintosh).
