### ISSUE TITLE
Can't retrieve information from UPDATE QUERY

### ISSUE THREAD

**Issue by wzrdtales** [mscdex/node-mariasql#107]
I just upgraded to 0.2.0 and just hit the first bug.

If you update an entry, the result stream is never going to be called and it is impossible to access the information property which is needed for informations like the last insert id.

To test it, take the following gist:
https://gist.github.com/wzrdtales/f679c3251ea3488a7fec

**Comment by mscdex** [comment]
This should be fixed as of 5643167a54 and v0.2.1.

**Comment by wzrdtales** [comment]
@mscdex Awesome, can confirm that this works now :)
