### ISSUE TITLE
Column metadata

### ISSUE THREAD

**Issue by Cheyenne55** [mscdex/node-mariasql#110]
Hello,

I saw that the columns metadatas are returned in the following format :
...
info: { numRows: '4',
    affectedRows: '4',
    insertId: '0',
    metadata: 
     { user_id: [Object],
       name: [Object],
       email: [Object],
       password: [Object] } } 

The column name is the key.
I think it would be easier to read if the column name is the value.
Something like this :
...
info: { numRows: '4',
    affectedRows: '4',
    insertId: '0',
    metadata: 
     { name: 'user_id',
       name: 'name',
       name: 'email',
       name: 'password' } } 

But in order to eventually access the underlying columns' properties stored in [Object], a new option would need to be introduced in the query method.
Maybe the properties can be nested after the name of the columns.

What do you think ?

**Comment by mscdex** [comment]
I'm -1 on this. It's easier to access the metadata if you already know the column name/alias (which you would have from row data for example). IMHO I don't think it is compelling enough to warrant a breaking change.

**Comment by Cheyenne55** [comment]
Well I said this because I am also using module Oracledb which returns results as I described.
That way it is very easy to dynamically create a table without knowing in advance the columns' name.
How would you do that with your method ?

**Comment by mscdex** [comment]
I'm not sure I understand what you're trying to do exactly. You're trying to create a table without knowing what the columns are supposed to be? How is that possible? Or are you trying to create a table in mysql/mariadb from metadata from oracledb or vice versa? Or something else?

**Comment by Cheyenne55** [comment]
I found the solution. It requires a module like merge (npm install merge).
Then you get my expected result form like this (for instance) :

res.status(200).send(merge({rows: result}, {columnsName: Object.keys(result.info.metadata)}));

What I was trying to do is to pass any sql request and get the results in a table that shapes dynamically with them.

Well I have just spend 3-4 hours finding the solution whereas with Oracledb it was straightforward.
