### ISSUE TITLE
Streaming doesn't seem to work properly with explicitly created connections

### ISSUE THREAD

**Issue by blah238** [mscdex/node-mariasql#114]
It looks like the query's `result` event never gets emitted if `connect()` is used. Normal (buffered) queries work fine with `connect()`, and streaming works fine without `connect()`. 

I'm using `mariasql@0.2.1` and Node 4.2.1. Environment is an Ubuntu Trusty 64-bit VM (VirtualBox/Vagrant) on a Windows 7 64-bit host. Database is MySQL 5.6.

Note that streaming with explicitly created connections worked in previous versions (0.1.x).

This works fine:

```js
// working.js

var Client = require('mariasql');

var c = new Client({
  host: '127.0.0.1',
  user: 'root',
  password: '',
  db: 'maria_test'
});

var query = c.query('SELECT * FROM users');

query.on('result', function (res) {
  console.log('stream begin');
  res.on('data', function (data) {
    console.log(data.id)
  });
}).on('end', function() {
  console.log('stream end');
});

c.on('end', function () {
  console.log('client end');
});

c.end();
```
Output:
```
vagrant@vagrant-ubuntu-trusty-64:~/maria-test$ node working.js
stream begin
1
2
3
stream end
client end
vagrant@vagrant-ubuntu-trusty-64:~/maria-test$
```

However, this fails (`result` is never emitted):

```js
// failing.js

var Client = require('mariasql');

var c = new Client();

c.connect({
  host: '127.0.0.1',
  user: 'root',
  password: '',
  db: 'maria_test'
});

c.on('ready', function () {
  console.log('ready');

  var query = c.query('SELECT * FROM users');

  query.on('result', function (res) {
    console.log('stream begin');
    res.on('data', function (data) {
      console.log(data.id)
    });
  }).on('end', function() {
    console.log('stream end');
  });

  c.end();
});

c.on('end', function () {
  console.log('client end');
});
```

Output:
```
vagrant@vagrant-ubuntu-trusty-64:~/maria-test$ node failing.js
ready
client end
vagrant@vagrant-ubuntu-trusty-64:~/maria-test$
```

Is this a bug or am I doing something wrong?

**Comment by mscdex** [comment]
I'm not able to duplicate the issue.

**Comment by blah238** [comment]
@mscdex Ok thanks for trying it. Anything I can do to help narrow it down? Is there a debug mode for this? What's your environment?

**Comment by mscdex** [comment]
I personally tested it on Windows and Ubuntu 14.10, but all of the tests use an explicit `connect()` so that would also include the CI machines too (whatever OS they have).

The only debug statements are in the actual binding right now, you could turn those on I guess. To do that change `DEBUG=0` to `DEBUG=1` at the top of `src/binding.cc` and do a `node-gyp build` in the `node_modules/node-mariasql` directory.

**Comment by Nibbler999** [comment]
Only seems to be reproducible on single core machines. I expect @blah238 only has a single core in the VM. #114 fixes it.

**Comment by blah238** [comment]
Just confirming that PR #115 indeed fixes this issue for me.
