### ISSUE TITLE
Column metadata undefined for non-SELECT queries

### ISSUE THREAD

**Issue by blah238** [mscdex/node-mariasql#116]
With both streamed and buffered queries, in 0.2.x, `data.info.metadata` and `rows.info.metadata` are undefined for DELETE and UPDATE queries. Is this intentional or perhaps just a bug?

**Comment by mscdex** [comment]
Queries that do not produce result sets (INSERT, UPDATE, DELETE, etc.) do not provide metadata. It's just how MySQL/MariaDB works.

**Comment by blah238** [comment]
@mscdex Thanks. I am not very famliar with MySQL/MariaDB, just trying to get 0.2.x working in [Knex](https://github.com/tgriesser/knex). I'll have to dig deeper then. Is there anything different with how `affectedRows` is returned? Seems I have to parse it to integer now, it is being returned as a string whereas if I'm not mistaken it was returned as an integer in 0.1.x.

**Comment by mscdex** [comment]
Yes, the reason is that those info numbers (affected rows, num rows, insert id) are all 64-bit unsigned integers. JavaScript cannot represent 64-bit integers (just doubles), so for consistency I leave them as strings so as not to lose precision.

**Comment by blah238** [comment]
@mscdex Got it, thanks for the clarification. I put a note about the info numbers change in the upgrading wiki page: https://github.com/mscdex/node-mariasql/wiki/Upgrading-v0.1.x-to-v0.2.x/_compare/349baa6ff68dc48e6eada4790a4842990c814e34...ad1a1ab972eb42fe7844a6f8c3c21b6df7c730f5
