### ISSUE TITLE
Stored Procedures: "Strange" result passed to query callback

### ISSUE THREAD

**Issue by Tharit** [mscdex/node-mariasql#118]
When using stored procedures in a query, the result object seems to behave weird - the array containing the rows and the "info" object is wrapped inside of another array with another object with an info property as follows:

```
con.query("CALL foo (...)", function(err, rows) {
 console.log(rows);
});

=> 

[ 
  [
    [row1],
    [row2],
    .....
    info: { numRows: '200',
      affectedRows: '200',
      insertId: '0',
      metadata: undefined }
  ],
  { info:
     { numRows: '0',
       affectedRows: '0',
       insertId: '0',
       metadata: undefined } } 
]
```

This is not covered in the documentation and seems unintentional.

**Comment by mscdex** [comment]
It's not explicitly covered in the readme, but it's a common thing that mysql/mariadb does. For stored procedures mysql always includes an "extra" result set that is an overall success/failure indicator of the call to the stored procedure.

You will see this same empty result set from the mysql command-line client for example:

```
MariaDB [(none)]> CREATE DATABASE IF NOT EXISTS `foo`;
Query OK, 1 row affected, 1 warning (0.01 sec)

MariaDB [(none)]> USE `foo`;
Database changed
MariaDB [foo]> delimiter //
MariaDB [foo]> CREATE PROCEDURE `testproc` () BEGIN SELECT 1; END//
Query OK, 0 rows affected (0.05 sec)

MariaDB [foo]> delimiter ;
MariaDB [foo]> CALL `testproc`;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

MariaDB [foo]> 
```

Whereas if you just did a normal `SELECT 1` you would just see:

```
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```

**Comment by Tharit** [comment]
Thanks a lot for the detailed answer!
Even though I've been using mysql for over a decade it seems I've somehow managed to miss this particular bit of knowledge :)
