### ISSUE TITLE
error while running npm install mariasql

### ISSUE THREAD

**Issue by tomlai19852004** [mscdex/node-mariasql#124]
I am using node.js 4.2.2 and npm 3.3.12 but receive the following error while run "npm install mariasql"

libtool: unrecognized option `-static'
Try `libtool --help' for more information.
make: *** [Release/taocrypt.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tomlai/Documents/projects/workspace/intralogue/webplatform/node-intralogue-webplatform/node_modules/mariasql
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPACKAGEJSON intralogue@3.3.12 No repository field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mariasql"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! mariasql@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mariasql@0.2.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomlai/Documents/projects/workspace/intralogue/webplatform/node-intralogue-webplatform/npm-debug.log

**Comment by mscdex** [comment]
You probably have libtool installed via homebrew or similar (you can check with `which libtool` and see if it's in `/usr/local/Cellar/...`), but you need to revert back to the system's (Xcode) copy of libtool temporarily. You might also be able to simply do `PATH=/usr/bin:$PATH npm install mariasql` too, but I don't have a mac to test it.

To temporarily replace homebrew's libtool, try:

```
brew unlink libtool
```

Then try `npm install mariasql` again. Then afterwards:

```
brew link libtool
```

**Comment by tomlai19852004** [comment]
Thanks that solve it.
