### ISSUE TITLE
Request with like don't work with 0.2

### ISSUE THREAD

**Issue by webconsulting** [mscdex/node-mariasql#128]
Dear all,
I have an issue with like SQL.
When i'm connect in command line to mysql and i execute this request :
Select * from mytable where myword like 'benoit';
I have a resultset with row : myword : benoît
with like in command line î == i == ï...

But when i use node-mariasql, the resultset is empty....

var sql = 'Select * from mytable where myword like \'benoit\'';
myMaria.query(sql,function(err,rows){
console.log(rows);
});

There is a bug with like sql ?
Thanks

**Comment by mscdex** [comment]
Did you try setting `charset: 'utf8'` in the connection config object or explicitly querying `SET NAMES 'UTF8'` first (and only once)?

**Comment by webconsulting** [comment]
with setting charset:utf8 in the connection config this issue is resolve !
Thanks for your help.
Regards
