### ISSUE TITLE
Is "streamHWM" working?

### ISSUE THREAD

**Issue by sharpart555** [mscdex/node-mariasql#139]
While streaming very large set of result, res.pause() causes too much memory usage.

I think "streamHWM" option will help this situation. But it doesn't.

Is "streamHWM" option working properly?

I'm using MySQL v5.6.17 and node-mariasql v0.2.5

**Comment by mscdex** [comment]
Can you show the relevant code you're using?

**Comment by sharpart555** [comment]
It's my code :

var option = {
	port:3306,
	user:'',
	password:'',
	host:'',
	db:'',
	connTimeout:10,
	charset:"UTF8",
	streamHWM:1024
};

var Mariasql = require('mariasql');
var sql = new Mariasql(option);


var q = "SELECT * FROM veryLargeTable";
sql.query(q, {useArray: true}).on('result', function (res) {
	res.on('data', function (row) {
		console.log(JSON.stringify(row));

		res.pause();   //<-- cause too much memory usage! It seems like background streaming still ongoing.
	});
}).on('end', function () {
	console.log("Done!");
});

**Comment by sharpart555** [comment]
Hmm... Am I misunderstand about "streamHWM" ..?

**Comment by sharpart555** [comment]
sorry, it works.

It was WebStorm execution environment problem.

**Comment by mscdex** [comment]
FWIW setting `streamHWM: 1024` means it should buffer at most 1024 rows in memory before (temporarily) stopping.
