### ISSUE TITLE
Unhandled exception instead of getting an error in callback func

### ISSUE THREAD

**Issue by v-vayer** [mscdex/node-mariasql#141]
When running a query and the user does not have sufficient rights, there's an unhandled exception instead of an error object in the callback function:

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: Access denied for user '***@***' to database '***'
    at Error (native)

**Comment by mscdex** [comment]
Can you show the code you're using?

**Comment by v-vayer** [comment]
Here's the code. User "guest" does not have a privellege to read from `testdb`.`testtbl`.

var maria = require('mariasql');
var conn = new maria({ host: '127.0.0.1', user: 'guest', password:'blah', db: 'testdb' });
conn.query('SELECT * FROM `testtbl`',
	(err, data) => {
		console.log(err);
	}
);

**Comment by mscdex** [comment]
What version of this addon are you using?

**Comment by v-vayer** [comment]
version 0.6.1

**Comment by mscdex** [comment]
Huh? The latest version is only v0.2.6.

**Comment by v-vayer** [comment]
My apologies, I mistakenly read the version of another module. What I have is 0.2.6 - the latest.

**Comment by mscdex** [comment]
Did you try attaching an `error` event handler on `conn`?

**Comment by v-vayer** [comment]
Brian, i've attached error to conn and found my mistake. Everything looks ok.
Thanks for your time!
