### ISSUE TITLE
Drop eval usage

### ISSUE THREAD

**Issue by steelbrain** [mscdex/node-mariasql#142]
This package uses `new Function` in `createRowBuilder` present in `$root/lib/Client.js`.

Eval usage disallows use of this module in [Electron](https://github.com/electron/electron)

The error it produces is
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

**Comment by mscdex** [comment]
Unfortunately I don't know enough about Electron to suggest anything. `new Function()` is used to improve performance, so it can't just be dropped.

**Comment by steelbrain** [comment]
Is the performance improvement significant? Also this is the same eval restriction that's found in chrome extensions and apps. It would be awesome to replace it with something elese

**Comment by mscdex** [comment]
Last I checked it was. It's basically used to avoid placing objects in dictionary mode and creating a bunch of hidden classes after object creation.

**Comment by steelbrain** [comment]
Okay then. For future visitors I suppressed the error by using the `loophole` module
