### ISSUE TITLE
build error on osx

### ISSUE THREAD

**Issue by mathnode** [mscdex/node-mariasql#143]
Hi, I have the following build error. Any ideas?

`12:39:33 ~ $ npm install mariasql --python=python2.7
|
> mariasql@0.2.6 install /Users/teatime/node_modules/mariasql
> node-gyp rebuild

  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aes.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aestables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/algebra.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/arc4.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/asn.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/bftables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/blowfish.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/coding.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/des.o
../deps/libmariadbclient/extra/yassl/taocrypt/src/des.cpp:227:5: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
    register int i,j,l;
    ^~~~~~~~~
../deps/libmariadbclient/extra/yassl/taocrypt/src/des.cpp:227:5: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
    register int i,j,l;
    ^~~~~~~~~
../deps/libmariadbclient/extra/yassl/taocrypt/src/des.cpp:227:5: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
    register int i,j,l;
    ^~~~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/dh.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/dsa.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/file.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/hash.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/hc128.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/integer.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md2.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md4.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md5.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/misc.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/rabbit.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/random.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/ripemd.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/rsa.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/sha.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/tftables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/twofish.o
  LIBTOOL-STATIC Release/taocrypt.a
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/buffer.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/cert_wrapper.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/crypto_wrapper.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/handshake.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/lock.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/log.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/socket_wrapper.o
../deps/libmariadbclient/extra/yassl/src/socket_wrapper.cpp:49:15: warning: unused variable 'SOCKET_EINVAL' [-Wunused-const-variable]
    const int SOCKET_EINVAL = EINVAL;
              ^
1 warning generated.
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/ssl.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/timer.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_error.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_imp.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_int.o
../deps/libmariadbclient/extra/yassl/src/yassl_int.cpp:912:12: warning: unused variable 'handshake_order' [-Wunused-const-variable]
const char handshake_order[] = "Out of order HandShake Message!";
           ^
1 warning generated.
  LIBTOOL-STATIC Release/yassl.a
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/client.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/client_plugin.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/mysql_async.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/my_time.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/pack.o
  CXX(target) Release/obj.target/clientlib/deps/libmariadbclient/sql/net_serv.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql/password.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/libmysql/errmsg.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/libmysql/libmysql.o
../deps/libmariadbclient/libmysql/libmysql.c:1421:12: warning: address of array 'net->last_error' will always evaluate to 'true' [-Wpointer-bool-conversion]
  if (net->last_error && net->last_error[0])
      ~~~~~^~~~~~~~~~ ~~
1 warning generated.
  LIBTOOL-STATIC Release/clientlib.a
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/array.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/charset-def.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/charset.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/errors.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/hash.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/list.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_arr_appstr.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_dirname.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_fn_ext.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_format.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_loadpath.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_pack.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_path.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_qsort.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_unixpath.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_wcomp.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mulalloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_access.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_alloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_compress.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_context.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_default.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_div.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_error.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_fopen.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_fstream.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_getsystime.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_getwd.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_init.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_lib.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_malloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_mess.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_once.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_open.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_pthread.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_read.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_seek.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_static.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_symlink.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_thr_init.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_write.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/safemalloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/string.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/thr_mutex.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/typelib.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_sync.o
../deps/libmariadbclient/mysys/my_sync.c:136:19: warning: unused variable 'cur_dir_name' [-Wunused-const-variable]
static const char cur_dir_name[]= {FN_CURLIB, 0};
                  ^
1 warning generated.
  LIBTOOL-STATIC Release/mysys.a
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_aes.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_md5.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_rnd.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_sha1.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_sha2.o
  LIBTOOL-STATIC Release/mysys_ssl.a
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/bchange.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/bmove_upp.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-big5.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-bin.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-cp932.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-czech.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-eucjpms.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-euc_kr.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-extra.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-gb2312.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-gbk.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-latin1.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-mb.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-simple.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-sjis.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-tis620.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-uca.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-ucs2.o
../deps/libmariadbclient/strings/ctype-ucs2.c:57:1: warning: unused function 'my_bincmp' [-Wunused-function]
my_bincmp(const uchar *s, const uchar *se,
^
1 warning generated.
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-ujis.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-utf8.o
../deps/libmariadbclient/strings/ctype-utf8.c:4894:19: warning: unused function 'bincmp' [-Wunused-function]
static inline int bincmp(const uchar *s, const uchar *se,
                  ^
../deps/libmariadbclient/strings/ctype-utf8.c:5066:1: warning: unused function 'my_tosort_utf8mb3' [-Wunused-function]
my_tosort_utf8mb3(MY_UNICASE_INFO *uni_plane, my_wc_t *wc)
^
../deps/libmariadbclient/strings/ctype-utf8.c:7279:1: warning: unused function 'bincmp_utf8mb4' [-Wunused-function]
bincmp_utf8mb4(const uchar *s, const uchar *se,
^
3 warnings generated.
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-win1250ch.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/dtoa.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/int2str.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/is_prefix.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/llstr.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/longlong2str.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/my_strtoll10.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/my_vsnprintf.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/str2int.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strcend.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strcont.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strend.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strfill.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmake.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmov_overlapp.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strnmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strxmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strxnmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/str_alloc.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/xml.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strnlen.o
  LIBTOOL-STATIC Release/strings.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/strings.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/teatime/node_modules/mariasql
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Darwin 15.4.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "mariasql" "--python=python2.7"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.2
npm ERR! code ELIFECYCLE

npm ERR! mariasql@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mariasql@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mariasql
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/teatime/npm-debug.log`


**System info:**
`12:53:42 ~ $ mysql -V
mysql  Ver 15.1 Distrib 10.1.11-MariaDB, for osx10.11 (x86_64) using readline 5.1
12:58:39 ~ $ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
12:58:43 ~ $ uname -a
Darwin ttmw 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
12:58:48 ~ $ npm -v
2.15.2
12:59:04 ~ $ node -v
v4.4.3`

**npm-debug-log:**
https://gist.github.com/mathnode/963c72feb0e3114e1d6d07130e2458ef

**Comment by mscdex** [comment]
Googling the python error seems to suggest it's something Python 3.x-related. I wonder if it's possible it's getting picked up instead of Python 2.7 somehow.

What does `npm install mariasql --python=python2.7 --loglevel=silly` output?

At the very least, you will probably want to post an issue on [`node-gyp`'s issue tracker](https://github.com/nodejs/node-gyp/issues) as this seems gyp-related and not anything to do with this addon.

**Comment by mathnode** [comment]
Yes you are correct it was python3 interfering, I just altered PATH while I installed mariasql.

`var Client = require('mariasql'),
    fs = require('fs'),
    ini = require('ini');

var my_cnf_path = process.env.HOME + '/.my.cnf'
var cnf = ini.parse(fs.readFileSync(my_cnf_path, 'utf-8'))

var c = new Client({
    host: cnf.vm.host,
    port: cnf.vm.port,
    user: cnf.client.user,
    password: cnf.client.password
});

c.query('SELECT @@version;', function(err, rows) {
    if (err)
        throw err;
    console.dir(rows);
});
c.end();
`

`16:54:13 tmp $ node test.js
[ { '@@version': '10.0.24-MariaDB' },
  info: { numRows: '1',
    affectedRows: '1',
    insertId: '0',
    metadata: undefined } ]`
