### ISSUE TITLE
ERROR NPM INSTALL 

### ISSUE THREAD

**Issue by pazalvin** [mscdex/node-mariasql#145]
please help me fix this error 

![centos](https://cloud.githubusercontent.com/assets/2208580/15175633/d64222ae-1799-11e6-809d-85a5314a935e.jpg)

My Enviroment:
Server : Centos 6
NodeVersion : 5.10
NPM Version: 3.8.3
Node-gyp Version: 3.3.1

**Comment by mscdex** [comment]
Screenshots are typically not very useful, posting the actual console text is much better.

However I'm going to guess you have an older compiler. You can check with `gcc -v`. You will need gcc/g++ 4.8 or newer.

**Comment by pazalvin** [comment]
![centos](https://cloud.githubusercontent.com/assets/2208580/15236201/048d884a-18f5-11e6-8cd0-46c4beb0b2d0.jpg)

it's working now thanks for the advice

**Comment by mlumbroso** [comment]
Hey,
first thanks for this great library :)
Why not indicate in the requirements gcc > 4.8 ? 
In CentOS 6, default version is 4.4.2 and I had to search for this closed issue to find why it wouldn't install.

**Comment by mscdex** [comment]
@mlumbroso The issue is that the build environment requirements come from node itself (which currently requires gcc/g++ 4.8.2+) and not this addon in particular. So *all* addons will have this requirement.

**Comment by mlumbroso** [comment]
Hi, I didn't know about this, can you share the reference to this?

Thanks :)

**Comment by mscdex** [comment]
https://github.com/nodejs/node/blob/cffbb326a2893348f137f8c53b141a61274742b1/BUILDING.md

**Comment by jimmyolo** [comment]
This is a great async lib for node operating on mariadb. I'm using mariadb 10.1.1.19(& connector c 2.2.3). For now, it work well for me. should this lib update for newer connector or mariadb version?

**Comment by mscdex** [comment]
@victor0801x Please open a new issue if you want to discuss something unrelated to the original topic.
