### ISSUE TITLE
unable to install on Windows 7

### ISSUE THREAD

**Issue by tomcon** [mscdex/node-mariasql#146]
Can someone help please?
It looks like the build might be targeting a very old version of .Net (v4.0.30319)
See also npm-debug.log below

Console window:
....
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3400): error C4430: missing type
 specifier - int assumed. Note: C++ does not support default-int [C:\Apps\app-a
mber\server\node_modules\mariasql\build\sqlclient.vcxproj]
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3400): error C2143: syntax error
 : missing ';' before '{' [C:\Apps\app-amber\server\node_modules\mariasql\build
\sqlclient.vcxproj]
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3400): error C2334: unexpected t
oken(s) preceding '{'; skipping apparent function body [C:\Apps\app-amber\serve
r\node_modules\mariasql\build\sqlclient.vcxproj]
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3402): error C2059: syntax error
 : 'return' [C:\Apps\app-amber\server\node_modules\mariasql\build\sqlclient.vcx
proj]
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3402): error C2238: unexpected t
oken(s) preceding ';' [C:\Apps\app-amber\server\node_modules\mariasql\build\sql
client.vcxproj]
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3403): error C2146: syntax error
 : missing ';' before identifier 'ByteLength' [C:\Apps\app-amber\server\node_mo
dules\mariasql\build\sqlclient.vcxproj]
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3403): error C2270: 'ByteLength'
 : modifiers not allowed on nonmember functions [C:\Apps\app-amber\server\node_
modules\mariasql\build\sqlclient.vcxproj]
c:\users\tc7\.node-gyp\4.2.2\include\node\v8.h(3403): fatal error C1003: error
count exceeds 100; stopping compilation [C:\Apps\app-amber\server\node_modules\
mariasql\build\sqlclient.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\bin\Node\node_modules\npm\node_mod
ules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\bin\\Node\\node.exe" "C:\\bin\\Node\\node_modules\\npm\\no
de_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

npm-debug.log
1152 info install mariasql@0.2.6
1153 verbose unsafe-perm in lifecycle true
1154 info mariasql@0.2.6 Failed to exec install script
1155 verbose unlock done using C:\Users\tc7\AppData\Roaming\npm-cache\_locks\mariasql-469635a8d05c6900.lock for C:\Apps\app-amber\server\node_modules\mariasql
1156 verbose stack Error: mariasql@0.2.6 install: `node-gyp rebuild`
1156 verbose stack Exit status 1
1156 verbose stack     at EventEmitter.<anonymous> (C:\bin\Node\node_modules\npm\lib\utils\lifecycle.js:214:16)
1156 verbose stack     at emitTwo (events.js:87:13)
1156 verbose stack     at EventEmitter.emit (events.js:172:7)
1156 verbose stack     at ChildProcess.<anonymous> (C:\bin\Node\node_modules\npm\lib\utils\spawn.js:24:14)
1156 verbose stack     at emitTwo (events.js:87:13)
1156 verbose stack     at ChildProcess.emit (events.js:172:7)
1156 verbose stack     at maybeClose (internal/child_process.js:818:16)
1156 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1157 verbose pkgid mariasql@0.2.6
1158 verbose cwd C:\Apps\app-amber\server
1159 error Windows_NT 6.1.7601
1160 error argv "C:\\bin\\Node\\node.exe" "C:\\bin\\Node\\node_modules\\npm\\bin\\npm-cli.js" "install" "mariasql"
1161 error node v4.2.2
1162 error npm  v2.14.7
1163 error code ELIFECYCLE
1164 error mariasql@0.2.6 install: `node-gyp rebuild`
1164 error Exit status 1
1165 error Failed at the mariasql@0.2.6 install script 'node-gyp rebuild'.
1165 error This is most likely a problem with the mariasql package,
1165 error not with npm itself.
1165 error Tell the author that this fails on your system:
1165 error     node-gyp rebuild
1165 error You can get their info via:
1165 error     npm owner ls mariasql
1165 error There is likely additional logging output above.
1166 verbose exit [ 1, true ]
1167 verbose unbuild node_modules\mariasql
1168 info preuninstall mariasql@0.2.6
1169 info uninstall mariasql@0.2.6
1170 verbose unbuild rmStuff mariasql@0.2.6 from C:\Apps\app-amber\server\node_modules
1171 info postuninstall mariasql@0.2.6
1172 silly gentlyRm C:\Apps\app-amber\server\node_modules\mariasql is being purged from base C:\Apps\app-amber\server
1173 verbose gentlyRm don't care about contents; nuking C:\Apps\app-amber\server\node_modules\mariasql
1174 silly vacuum-fs purging C:\Apps\app-amber\server\node_modules\mariasql
1175 silly vacuum-fs quitting because other entries in C:\Apps\app-amber\server\node_modules

**Comment by mscdex** [comment]
What version of VS are you using? IIRC you need 2013 or newer and according to [node-gyp's readme](https://github.com/nodejs/node-gyp/blob/master/README.md), [.NET 4.5.1](http://www.microsoft.com/en-us/download/details.aspx?id=40773)+ if you're on Vista or 7/Server 2008 (which it seems you are).

**Comment by tomcon** [comment]
@mscdex re-installed a later version of VS and although there are a number of yellow messages it seems to be working fine now. Many thanks!
