### ISSUE TITLE
Error return more friendly

### ISSUE THREAD

**Issue by rpaggi** [mscdex/node-mariasql#152]
Hello!

Anyone have any idea how to change the error return to an json format? Today we have the following format:
{ [Error: Unknown column 'teste' in 'field list'] code: 1054 }

anyone have any ideia how to change some as 
{
Error: Unknown column 'teste' in 'field list',
code: 1054 
}
or can tell me how i read the Error string?

Thanks

**Comment by mscdex** [comment]
Errors are instances of the `Error` object, so all the usual properties are there. The error message string itself is available on the `.message` property.

If you still want to convert an `Error` instance to a JSON string, you can use a solution like [this](http://stackoverflow.com/a/20405830).
