### ISSUE TITLE
Dockerized node instance fails to load mariasql

### ISSUE THREAD

**Issue by RobiFerentz** [mscdex/node-mariasql#164]
The docker build command seems to pass. However, when the mariasql client is created (starting the express js app inside Docker) it fails.

`Error: Cannot find module '../build/Debug/sqlclient'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/mariasql/lib/Client.js:13:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

I tried building with different version of node (6.5, 6.8 and 6.9) but each build has only one version of node installed. 

Doesn't seem to be an issue on my mac, but inside docker it failed every time.

**Comment by mscdex** [comment]
Are you building on the same platform and with the same major version of node? If you want, you can temporarily comment out the the try-catch and the loading of the debug version in lib/Client.js and it will throw with the real error.

**Comment by RobiFerentz** [comment]
Well, I thought it might have something to do with me running docker build on my mac rather on some other machine (linux).
Turns out I was right. I cloned my app on an ec2 machine and ran docker build on that machine and everything seems to work just fine, no error when running the node process. 
So it could be that it's a docker / docker for mac problem rather than an issue with this package. I'll keep checking.

**Comment by mscdex** [comment]
Yeah, compiled addons can only be used on the same platform with the same major version of node. If either of those change you will need to recompile/reinstall the addon. I'm not familiar enough with Docker, but I'm guessing the compilation was actually happening within the mac environment but then being used in Linux.

**Comment by RobiFerentz** [comment]
@mscdex Your last comment clinched it for me. The problem was that I followed instructions a little too closely from [here](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/).

Changing the dockerfile around a bit solved the issue. Two copy statements (in the link above) exist when only one should, since the second one erases node_modules with the local node_modules (compiled for osx, of course) and so things don't work. 
If I copy the entire thing first, delete node_modules and only then run npm install, everything is peachy.

Thank you so much for pointing me in the right direction, I'm a newbie with docker myself.
