### ISSUE TITLE
Nw.js error

### ISSUE THREAD

**Issue by ghost** [mscdex/node-mariasql#169]
I used nwjs (old Node-Webkit) and i have 2 errors.
1) First error is that it can't find Debug module

> Uncaught Error: Cannot find module '../build/Debug/sqlclient'
>     at Function.Module._resolveFilename (module.js:494:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:522:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous>
> \node_modules\mariasql\lib\Client.js:13:11)
>     at Module._compile (module.js:595:32)
>     at Object.Module._extensions..js (module.js:610:10)
>     at Module.load (module.js:512:32)
>     at tryModuleLoad (module.js:471:12)
>     at Function.Module._load (module.js:463:3)

2) Second error is:

> Uncaught Error: A dynamic link library (DLL) initialization routine failed.
> node_modules\mariasql\build\Debug\sqlclient.node
>     at Object.Module._extensions..node (module.js:640:18)
>     at Module.load (module.js:512:32)
>     at tryModuleLoad (module.js:471:12)
>     at Function.Module._load (module.js:463:3)
>     at Module.require (module.js:522:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous>
> node_modules\mariasql\lib\Client.js:13:11)
>     at Module._compile (module.js:595:32)
>     at Object.Module._extensions..js (module.js:610:10)
>     at Module.load (module.js:512:32)

Anyone know how to solve this problem?

**Comment by mscdex** [comment]
Comment out all of the `try { } catch () {}` in node_modules/mariasql/lib/Client.js except for the `require()` line for the Release version of the addon and it should throw the real error.

**Comment by ghost** [comment]
Sorry i didn't write it but i do that and real error is second error in my first post.

> Uncaught Error: A dynamic link library (DLL) initialization routine failed.
> node_modules\mariasql\build\Release\sqlclient.node
> at Object.Module._extensions..node (module.js:640:18)
> at Module.load (module.js:512:32)
> at tryModuleLoad (module.js:471:12)
> at Function.Module._load (module.js:463:3)
> at Module.require (module.js:522:17)
> at require (internal/module.js:20:19)
> at Object.
> node_modules\mariasql\lib\Client.js:13:11)
> at Module._compile (module.js:595:32)
> at Object.Module._extensions..js (module.js:610:10)
> at Module.load (module.js:512:32)

**Comment by mscdex** [comment]
Did you follow the instructions [here](https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons)?

**Comment by ghost** [comment]
Thanks for help. Now my program is safe and sound ;)

**Comment by ghost** [comment]
close
