### ISSUE TITLE
Can't install with GCC 4.4.7

### ISSUE THREAD

**Issue by mlumbroso** [mscdex/node-mariasql#178]
Hi,

thanks for this great library.

I couldn't install it with default CentOS 6 gcc/g++ version (4.4.7)

I had to install 4.8.x to make the node-gyp rebuild works.
I don't know from which exact version it's starting to work, but it might be worth adding it to the requirements (I guess it's min. 4.7.x)

Thanks

**Comment by mscdex** [comment]
The build requirements for this addon are the same as for [node itself](https://github.com/nodejs/node/blob/master/BUILDING.md) and [all node addons](https://github.com/nodejs/node-gyp/blob/master/README.md). Currently this means a minimum gcc version of 4.8.5+.
