### ISSUE TITLE
~Installation error~ Kindly confirm the dependency details to use this module. 

### ISSUE THREAD

**Issue by ghost** [mscdex/node-mariasql#187]
Kindly confirm the dependency details to use this module. 

1.
Python vesion should be >=2.5 and <= 3.0

2.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  

What else is required ??

**Comment by mscdex** [comment]
The general build environment requirements for all node addons are located in the node-gyp readme [here](https://github.com/nodejs/node-gyp#on-windows).

**Comment by ghost** [comment]
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
