### ISSUE TITLE
It seems, Mysql package supports mariaDB as well 

### ISSUE THREAD

**Issue by ghost** [mscdex/node-mariasql#188]
Team, 
I have a sample program to connect MySql server. The same program is working fine for MariaDB as well. 
Just replaced mySQL host name with MariaDB host. 

Shall i use mysql package to connect mariaDB ? Is it compatible ? 

https://www.npmjs.com/package/mysql

**Comment by mscdex** [comment]
You can use whatever you want. MySQL, MariaDB, Percona, etc. are all compatible with each other (at the protocol level), so all drivers for such databases should all work on any of those servers.

**Comment by ghost** [comment]
Thanks a lot for your clarification.
