### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by romgerman** [mscdex/node-mariasql#193]
Is this repo dead?

**Comment by ghost** [comment]
Yes, I believe it is dead. There have been outstanding pull requests with valid patches that have been ignored for over a year.

If your looking at node-mariasql to get good SQL performance, you might want to reconsider  https://github.com/mysqljs/mysql they have made major improvements to performance and the published benchmarks you read online are very out of date. Read more about the performance improvements at https://github.com/felixge/faster-than-c
