### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by joelabair** [mscdex/node-mariasql#22]
I've written a small suite of jasmine tests for a few db models using node-mariasql.  On my desktop PC (Fedora 17), tests run as expected.  Yet, in a VMware vm and VirtualBox vm running CentOS 5.9 and CentOS 6.4, and on my RackSpace Cloud Server i get the following:

bash >jasmine-node spec/
.node: ../src/binding.cc:550: static void Client::cb_poll(uv_poll_t*, int, int): Assertion `status == 0' failed.
Aborted
- 
  bash >npm ls mariasql
  └── mariasql@0.1.17 

not sure how to debug further.

**Comment by blah238** [comment]
Looks like the fix for this was undone in e933f1b7db2c5fce78495d49dc23913fd840e019, resulting in #113
