### ISSUE TITLE
prepared statements

### ISSUE THREAD

**Issue by AndreasMadsen** [mscdex/node-mariasql#25]
As I understand it `.prepared` _only_ escapes the values and don't create a _true prepared statement_.

Is this true? If so, would it be possible to implement?

**Comment by mscdex** [comment]
My last comment still stands. While working on the [rewrite](https://github.com/mscdex/node-mariasql/tree/rewrite), I spent at least a good portion of a day trying to come up with a *good* way to incorporate the (async) libmariadbclient prepared statements API. However I do not currently see any sane way to do this. If someone is able to come up with something clean, simple, and usable, I am open to PRs.

The alternative until then might be to use the [SQL syntax for prepared statements](http://dev.mysql.com/doc/refman/5.0/en/sql-syntax-prepared-statements.html) if you need support for that kind of thing.
