### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by LuckyWolf19** [mscdex/node-mariasql#30]
I got the following errors when attempting to install. Note that I attempted to install once and got an error due to the lack of Python installed. I installed python and ran the mariasql install again. Also note, after I got the errors below, I looked in the node_modules folder and there is no mariasql folder there.

My installed components are:

- Windows 2012 server 64-bit
- MariaDB v10.0.4. Alpha
- node.js v0.10.15 for 64-bit Windows
- npm install underscore  (v1.5.1)
- npm install express (v3.3.4)
- npm install mariasql (0.1.19)
     - Python v2.7.5 to C:\Python27\
     - New environment variable called PYTHON set to C:\Python27\python.exe

ERROR MESSAGES:

C:\code>npm install mariasql
npm http GET https://registry.npmjs.org/mariasql
npm http 304 https://registry.npmjs.org/mariasql
npm http GET https://registry.npmjs.org/lru-cache/2.3.0
npm http 304 https://registry.npmjs.org/lru-cache/2.3.0

> mariasql@0.1.19 install C:\code\node_modules\mariasql
> node-gyp rebuild

C:\code\node_modules\mariasql>node "C:\Program Files\nodejs\node_modules\npm\bin
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v0.10.15/node-v0.10.15.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.15/node-v0.10.15.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.15/node.lib
gyp http GET http://nodejs.org/dist/v0.10.15/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.15/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.15/node.lib
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\code\node_modules\mariasql\build\deps\libmariadbclient\libmysql\clientlib.vc
xproj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.prop
s" was not found. Confirm that the path in the <Import> declaration is correct,
 and that the file exists on disk.
C:\code\node_modules\mariasql\build\deps\libmariadbclient\mysys\mysys.vcxproj(1
8,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was
not found. Confirm that the path in the <Import> declaration is correct, and th
at the file exists on disk.
C:\code\node_modules\mariasql\build\deps\libmariadbclient\strings\strings.vcxpr
oj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props"
was not found. Confirm that the path in the <Import> declaration is correct, an
d that the file exists on disk.
C:\code\node_modules\mariasql\build\deps\libmariadbclient\extra\yassl\taocrypt\
taocrypt.vcxproj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.D
efault.props" was not found. Confirm that the path in the <Import> declaration
is correct, and that the file exists on disk.
C:\code\node_modules\mariasql\build\deps\libmariadbclient\vio\vio.vcxproj(18,3)
: error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not
found. Confirm that the path in the <Import> declaration is correct, and that t
he file exists on disk.
C:\code\node_modules\mariasql\build\deps\libmariadbclient\extra\yassl\yassl.vcx
proj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props
" was not found. Confirm that the path in the <Import> declaration is correct,
and that the file exists on disk.
C:\code\node_modules\mariasql\build\deps\libmariadbclient\zlib\zlib.vcxproj(18,
3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was no
t found. Confirm that the path in the <Import> declaration is correct, and that
 the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\code\node_modules\mariasql
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

C:\code>

**Comment by mscdex** [comment]
The [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite) now uses `nan` for wider node compatibility.
