### ISSUE TITLE
Query event is lost if combined with abort and error with multiple statements enabled

### ISSUE THREAD

**Issue by roamm** [mscdex/node-mariasql#35]
```javascript
var Client = require('mariasql');

var c = new Client();
c.connect({multiStatements: true});

var cnt = 0;
results = c.query('SELECT 1; SELECT 2 FROM nonexists; SELECT 3');
results.on('result', function(query) {
  cnt++;
  query.on('abort', function() { console.log('Query Aborted'); });
  query.on('error', function(err) { console.log('Query Error', err); });
  query.on('end', function(info) { console.log('Query Ended', info); });
  if (cnt == 2) query.abort();
});
results.on('abort', function() { console.log('Result Aborted'); });
results.on('end', function() { console.log('Result Ended'); });
```
We would expect following output

    Query End { insertId: 0, affectedRows: 0, numRows: 1 }
    Query Aborted / Query Error // which one to expect is not specified in the doc...
    Result Ended

While actually what we get is

    Query Ended { insertId: 0, affectedRows: 0, numRows: 1 }
    Result Ended

Event to the second query is missing.

Interestingly, this may happen to each query in the Results except for the first one.

**Comment by mscdex** [comment]
v0.2.0 is released now and is more or less a complete rewrite. The `abort()` behavior has changed and now lives on the connection object. If you are still encountering this issue, let me know.
