### ISSUE TITLE
How to enable and to display connection option metadata?

### ISSUE THREAD

**Issue by innc** [mscdex/node-mariasql#51]
Hello :),
probably someone can help me.

I used  "felixge's - node-mysql" for my thesis. There i got column-informations (variable "fields") like name, table, db, orgTable for each column of the returned query-data.

Now i am searching something similar for mariasql.
I found this commit:
"Added metadata option to return column type and charsets"

I tried to enable for connection by setting "metadata = true".
```JavaScript
c.connect({
  host: '127.0.0.1',
  user: 'foo',
  password: 'bar',
  metadata: true
});
```
Then i tried to get the metadata output in this was, but i failed:
```JavaScript
c.query('SHOW DATABASES')
 .on('result', function(res) {
   res.on('row', function(row, metadata) {
     console.log('Result row: ' + inspect(row));
     console.log(metadata);  // added code line, but undefined returned
   })
   .on('error', function(err) {
     console.log('Result error: ' + inspect(err));
   })
   .on('end', function(info) {
     console.log('Result finished successfully');
   });
 })
 .on('end', function() {
   console.log('Done with all results');
 });
```

Now I have 2 questions and i hope someone can help or give an advice.
1.) How can i get metadata?
2.) Is there a plan to extend such metadata informations or how I can extend it?

**Comment by mscdex** [comment]
Can you explain what you mean by "extending" the metadata? What information are you missing?

**Comment by innc** [comment]
Hello, 
thank you for asking, but I added the metadata information required for my thesis project and you merged it into node-mariasql some time ago. Look here at pull request "Metadata information extension #52".

There are more metadata, which could be basically supported, look here:
http://dev.mysql.com/doc/refman/5.6/en/c-api-data-structures.html

**Comment by mscdex** [comment]
v0.2.0 is released now and is more or less a complete rewrite. This version adds the column flags in the metadata object. If you need some other missing metadata, let me know which you are looking for.
