### ISSUE TITLE
Uncatchable Error "Not ready to query"

### ISSUE THREAD

**Issue by Tharit** [mscdex/node-mariasql#55]
Using the module with our SQL database, I frequently get an uncatched exception "Not ready to query". I've looked at your code, and it seems to me that this error is not handled by you, and can not be catched reliably, as it occurs in a function that is called via process.nextTick.

Stacktrace:
[...]/node_modules/mariasql/lib/Client.js:340
      this._client.query(this._curResults._query, this._curResults._useArray);
                   ^
Error: Not ready to query
    at Client._processQueries ([...]/node_modules/mariasql/lib/Client.js:340:20)
    at [...]/node_modules/mariasql/lib/Client.js:239:38

Edit: if relevant, database is running MySQL (14.14 Distrib 5.1.73, for debian-linux-gnu (x86_64) using readline 6.1)

**Comment by mscdex** [comment]
This is fixed in the [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite).
