### ISSUE TITLE
Question: How to set enable-local-infile?

### ISSUE THREAD

**Issue by ltamrazov** [mscdex/node-mariasql#59]
Can't get this to work. I saw it as an option in the client.c file, but can't figure out how to set it from the script. Is there a flag, or some other option? 

Thanks!

UPDATE:

Found this in MySQL documentation:
If you use LOAD DATA LOCAL in Perl scripts or other programs that read the [client] group from option files, you can add the local-infile=1 option to that group. However, to keep this from causing problems for programs that do not understand local-infile, specify it using the loose- prefix:

[client]
loose-local-infile=1

However it still didn't work which makes me think its a bug in the C client.

**Comment by digipigeon** [comment]
+1

**Comment by digipigeon** [comment]
Quick check of the source code, I saw

local_infile

when I set this in the connection params to true it worked fine.

**Comment by mscdex** [comment]
v0.2.0 is released now and is more or less a complete rewrite. Additionally, the `local_infile` connection config option is now documented. If you are encountering an issue with it, let me know.
