### ISSUE TITLE
Bug: CASE WHEN not working properly

### ISSUE THREAD

**Issue by van-nguyen** [mscdex/node-mariasql#76]
Hi there, this problem I'm having is pretty weird..

```
REPLACE INTO country SELECT c.code,c.name,c.slug,c.latitude,c.longitude,
SUM(a.number_of_reviews) as reviews,(
  CASE
    WHEN reviews > 100000 THEN 0.8
    WHEN reviews > 50000 THEN 0.7
    WHEN reviews > 20000 THEN 0.6
    ELSE 0.5
  END
) as priority FROM country c
JOIN agoda a ON (c.code=a.code)
GROUP BY a.code
```

When I run this normally with Sequel Pro, it works. But when I put it through this driver it's only picking up the ELSE part of the CASE i.e. "0.5". Any ideas? Thanks.

**Comment by mscdex** [comment]
I'm not able to duplicate this. A plain query string like that (with no variable replacement/substitution) is passed as-is to the underlying libmariadbclient functions.

If you get a chance, please try with the [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite), which contains a newer version of libmariadbclient, which may include a bug fix for your particular issue.
