### ISSUE TITLE
Segmentation fault on connect (with wrong host)

### ISSUE THREAD

**Issue by lachrist** [mscdex/node-mariasql#78]
A mariadb server have a user at host 127.0.0.1. When I omit the host into the options for the connection, I get a segmentation fault (during the connect call).
My system is:
centos 6.5
node 0.10.26
mariadb 10.0.10
mariasql 0.1.21

Thanks for the great works anyway :)

**Comment by mscdex** [comment]
Can you try with the [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite)?

**Comment by lachrist** [comment]
I do not have time right now.
But I will try my best to reproduce the bug next week.

**Comment by mscdex** [comment]
v0.2.0 is released now and is more or less a complete rewrite. If you are still encountering this issue, let me know.

**Comment by acoulon99** [comment]
I was seeing this behavior as well.
node: 4.2.1
mariasql: 0.2.1

Behavior is normal if there's a mariaDB instance running where `host` is, but if mariaDB isn't installed, it creates a segmentation fault:

```
nodejs: ../src/binding.cc:916: static void Client::cb_poll(uv_poll_t*, int, int): Assertion `status == 0' failed.
Aborted (core dumped)
```

**Comment by mscdex** [comment]
@acoulon99 Can you test with the master branch? This was fixed recently.

**Comment by acoulon99** [comment]
Sure thing, I'll update when I do

**Comment by acoulon99** [comment]
Working well! :)
