### ISSUE TITLE
how can i use transaction??

### ISSUE THREAD

**Issue by c941010623** [mscdex/node-mariasql#79]
i want use transaction

when commit
when rollback

have ex???

**Comment by mscdex** [comment]
You can use transactions by using the usual MySQL/MariaDB queries (e.g. `START TRANSACTION`, `COMMIT`, `ROLLBACK`, etc.). However you should be aware that all queries are queued up, so if you want to roll back at any given moment, you will have to use a library such as [`async`](https://github.com/caolan/async) to do your own queueing to make sure the rollback gets done "immediately".
