### ISSUE TITLE
Not opening connection before querying doesn't produce error.

### ISSUE THREAD

**Issue by AbijeetP** [mscdex/node-mariasql#80]
I have the following code - 
```
this.client = new Client();
this.client.query(query, data).on('result', function(res) {		
		res.on('row', function(row) {
			console.log(row);
			response.push(row);
		}).on('error', function(err) {
			logger.info(err);
			cb(err, response);
			res.abort();
		});
	}).on('error', function(err) {
		logger.info("In error");		
		cb(err);		
	}).on('end', function() {
		logger.info("In end...");
		if (closeConnection !== undefined && closeConnection === false) {
			this.client.end();
		}
		cb(null, response, info);
	}).on('abort', function() {
		logger.info("In abort...");
	});
```

Here the connection has not been opened before calling the `query` method. 

### Expected Result 
The error callback for the `Result` object should fire.

### Actual Result
 None of the callbacks fire, and the code runs forever.

### Workaround
Simply check if the client is connected before executing the query. I've implemented this in the wrapper library I'm creating, but maybe the module should complain if the connection hasn't been opened before trying to run the query.

**Comment by mscdex** [comment]
The connection behavior is still similar for the [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite) with the exception that the connection instance isn't ref'ed until connect time, so the process should not get stuck open unnecessarily.
