### ISSUE TITLE
Error: Not ready to query

### ISSUE THREAD

**Issue by Abijeet** [mscdex/node-mariasql#81]
I'm currently having this issue mentioned in - #55 and #15 

# Scenario

The way I understand it, is this is how it happens - 

- You are creating a user in your database. Before creating your user, you want to check if another user with that email address already exists.
- You use the async module, to have two queries run in the waterfall model.The first function in the model checks if a user exists using a mariasql client object -` mSQLClient`. At the end of the function, it calls - `mSQLClient.end()`
- You find that the email address does not exist in your database, so it's time to create the user.
- You then starting using the same client object to create the user (rather than creating a new one) in the second function  because the following returns true - 
````
if (mSQLClient && mSQLClient.connected)
````
- Finally when the second method calls `mSQLClient.query()` it receives the error - `Error: Not ready to query`

# Potential Cause

The way I see it, there seems to be difference between what's in the JS variable and what's in the C++ variable. See [the following file in binding.cc](https://github.com/mscdex/node-mariasql/blob/0c689599fdb8aab0e2f2aec65a40a0f628106fc6/src/binding.cc#L1018)

**Comment by mscdex** [comment]
If you get a chance, please try with the [rewrite](https://github.com/mscdex/node-mariasql/tree/rewrite), which is almost complete now.

**Comment by mscdex** [comment]
v0.2.0 is released now and is more or less a complete rewrite. If you are still encountering this issue, let me know.

**Comment by RAdevelop** [comment]
I have the same problem:
Error: Not ready to query
    at Error (native)
    at Client._processQueue (/path/to/project/node_modules/mariasql/lib/Client.js:588:18)
    at Client._onidle (/path/to/project/node_modules/mariasql/lib/Client.js:444:8)

I try to get user data from database.
and then update same filed for user...

1) function get user data
2) function update user data

**Comment by mscdex** [comment]
@RAdevelop Can you share a simple, minimal, and reproducible code example?

If not, can you change `#define DEBUG 0` to `#define DEBUG 1` at the top of `./node_modules/mariasql/src/binding.cc`, rebuild the addon (`node-gyp rebuild` -- you may need to `npm install node-gyp -g` if that doesn't work at first) and post the debug output somewhere?

**Comment by Abijeet** [comment]
@mscdex - I'll try to reproduce this issue again this week. I got busy and wasn't able to test it with the 0.2.* release.

**Comment by RAdevelop** [comment]
@mscdex 
this is jast as example.
It's my first steps in NodeJS pogramming. May be, I do something wrong in async programming.

```javascript
var MariaSQLClient = require('mariasql');
var AppConfig = require('app/config');
var c = new MariaSQLClient({
	host:       AppConfig.db.mysql.host,
	user:       AppConfig.db.mysql.user,
	password:   AppConfig.db.mysql.password,
	db:         AppConfig.db.mysql.dbname,
	charset:    AppConfig.db.mysql.charset
});

var uId = 1;

var getU = function (uId, cb)
{
	var sql = "SELECT u_id, u_mail, u_date_visit FROM `users` WHERE u_id = ?;";
	var sqlData= [uId];
	c.query(sql, sqlData, { useArray: true }, function(err, result){
		
		c.end();
		
		if(err && cb) return cb(err, null);
		else {
			console.log('do something with result');
			console.log(result);
			
			if(cb) return cb(null, result);
		}
	});
}

var updateU = function(uId, cb){
	
	var sql = 'UPDATE `users` SET u_date_visit = ? WHERE u_id = ?';
	var sqlData = [now_ts, uId];
	var now_ts = Date.now()/1000;
	var prep = c.prepare(sql);
	
	c.query(prep(sqlData), function(err, result) {
		c.end();
		
		if(err && cb) return cb(err, null);
		else {
			console.log('do something with result');
			console.log(result);
			
			if(cb) return cb(null, result);
		}
	});
};

getU(uId, function(err, res){
	if(err)
	{
		console.log(err);
		return;
	}
	console.log(res);
	updateU(uId, function(err, res){
		if(err)
		{
			console.log(err);
			return;
		}
		console.log(res);
	});
});
```
And result is

> $ node test.js
> do something with result
> [ [ '1', 'myemail@address.com', '0' ],
>   info: { numRows: '1',
>     affectedRows: '1',
>     insertId: '0',
>     metadata: undefined } ]
> [ [ '1', 'myemail@address.com', '0' ],
>   info: { numRows: '1',
>     affectedRows: '1',
>     insertId: '0',
>     metadata: undefined } ]
> /path/to/project/node_modules/mariasql/lib/Client.js:588
>     this._handle.query(req.str,
>                  ^

> Error: Not ready to query
>     at Error (native)
>     at Client._processQueue (/path/to/project/node_modules/mariasql/lib/Client.js:588:18)
>     at Client._onidle (/path/to/project/node_modules/mariasql/lib/Client.js:444:8)
> $


PS. sorry for my english :)

**Comment by mscdex** [comment]
@RAdevelop Ah ok, it's because you're ending the connection after the first query, so the connection is either in the process of closing or is already closed by the time you go to perform your second (update) query.

**Comment by RAdevelop** [comment]
@mscdex 
So, in my case I must recreate DB client for second function "updateU"?
(before calling second update query)

**Comment by mscdex** [comment]
@RAdevelop no, just remove `c.end()` from your first query callback.

**Comment by RAdevelop** [comment]
I figured out. 
I call c.end() after calling first callback and I removed c.end() from second function.

```javascript
var getU = function (uId, cb)
{
	var sql = "SELECT u_id, u_mail, u_date_visit FROM `users` WHERE u_id = ?;";
	var sqlData= [uId];
	c.query(sql, sqlData, { useArray: true }, function(err, result){
		
		if(err && cb) return cb(err, null);
		else {
			console.log('do something with result');
			console.log(result);
			
			if(cb) {
				cb(null, result);
			}
			c.end();
		}
	});
}

var updateU = function(uId, cb){
	
	var sql = 'UPDATE `users` SET u_date_visit = ? WHERE u_id = ?;';
	var sqlData = [now_ts, uId];
	var now_ts = Date.now()/1000;
	var prep = c.prepare(sql);
	
	c.query(prep(sqlData), function(err, result) {
		
		if(err && cb) return cb(err, null);
		else {
			console.log('do something with result');
			console.log(result);
			
			if(cb) return cb(null, result);
		}
	});
};

getU(uId, function(err, res){
	if(err)
	{
		console.log(err);
		return;
	}
	console.log(res);
	updateU(uId, function(err, res){
		if(err)
		{
			console.log(err);
			return;
		}
		console.log(res);
	});
});
```
Thanx a lot for Yours help! And have a nice day :)
