### ISSUE TITLE
Support Promises

### ISSUE THREAD

**Issue by steelbrain** [mscdex/node-mariasql#85]
Promises are a great way to write less and do more, It would be great to have Node-MariSQL supporting it.

**Comment by jgkennedy** [comment]
How does this stack up? https://github.com/lukequest/mariadb-transact

**Comment by steelbrain** [comment]
I made my own https://github.com/steelbrain/mariasql-promise :stuck_out_tongue_winking_eye:

**Comment by alexpts** [comment]
+1

**Comment by jomel** [comment]
@mscdex - now that promises and async/await are in much more mainstream use, is there a plan to add built-in promise support?
