### ISSUE TITLE
Add support for node 0.11

### ISSUE THREAD

**Issue by nunorafaelrocha** [mscdex/node-mariasql#86]
It would be great to have support for node 0.11 :smile:

**Comment by davidfregoli** [comment]
yeah, 0.12 (which is 0.11 made stable) is a few weeks away and many folks on 0.10 are waiting for it to  flip the switch.
It would be bad having this lib holding me back

**Comment by mscdex** [comment]
"a few weeks away" -- I got a chuckle out of that one :laughing:

But seriously, I am open to pull requests to `nan`-ify the module. I just don't have the time currently.

**Comment by nicokaiser** [comment]
There is a fork by @Leonidaz who seems to work on Node 0.12 (`nan`) support! Yeah!
https://github.com/Leonidaz/node-mariasql/

**Comment by Leonidaz** [comment]
we're just waiting form @mscdex to do some testing and performance regressions before merging.  maybe there is a faster way to do some string creation.

**Comment by nicokaiser** [comment]
@Leonidaz That's awesome! Thanks for the great work!

**Comment by mscdex** [comment]
The work from @Leonidaz was landed in aaea5a50e7. I encourage everyone to also give the [rewrite](https://github.com/mscdex/node-mariasql/tree/rewrite) a try. Just about all features are implemented.

**Comment by nunorafaelrocha** [comment]
:+1:
