### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by igittGit** [mscdex/node-mariasql#88]
````
> mariasql@0.1.21 install /home/ich/node/project/node_modules/mariasql
> node-gyp rebuild

make: Entering directory `/home/ich/node/project/node_modules/mariasql/build'
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aes.o
make: g++: Command not found
make: *** [Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aes.o] Error 127
make: Leaving directory `/home/ich/node/project/node_modules/mariasql/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ich/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "node" "/home/ich/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ich/node/project/node_modules/mariasql
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "node" "/home/ich/.nvm/v0.10.36/bin/npm" "install" "mariasql"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! mariasql@0.1.21 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mariasql@0.1.21 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ich/node/project/npm-debug.log

**Comment by mscdex** [comment]
You're missing build tools required to compile node addons: `make: g++: Command not found`

**Comment by igittGit** [comment]
````sudo apt-get install build-essential g++```` helped

Thank you

**Comment by havoc74** [comment]
I am having this same issue, but I do have build-essential and g++ installed. Here's my output:

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-28-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mariasql
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.16.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "mariasql"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! mariasql@0.1.21 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mariasql@0.1.21 install script 'node-gyp rebuild'.

Thanks for any help :)
