### ISSUE TITLE
nwjs 0.12.0 support?

### ISSUE THREAD

**Issue by Extarys** [mscdex/node-mariasql#92]
Does mariasql currently support nwjs 0.12.0?

Trying to install it using `sudo npm install mariasql --save --python=python2.7` throw the following js error in chromium: `Uncaught Error: Module version mismatch. Expected 43, got 14.`

Is there any workaround?

Thanks

**Comment by mscdex** [comment]
What `mariasql` version are you using? v0.1.22 uses `nan`, so it should support node 0.8 through 0.12 and io.js.
