### ISSUE TITLE
gyp: Call to 'node -e "require('nan')"' returned exit status 127

### ISSUE THREAD

**Issue by nevienc** [mscdex/node-mariasql#96]
When installing:
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp,

I think there should be now used nodejs instead of node.

**Comment by mscdex** [comment]
If you're on Debian and you did `apt-get install nodejs` you will need to also `apt-get install nodejs-legacy` to get the `node` symlink.

**Comment by atos-ari-aeon** [comment]
which version of node are you using? The GE needs to be run using v0.10.x

**Comment by intercake** [comment]
Thanks mscdex, sorted my problems :+1:
