### ISSUE TITLE
Debugging apparent connection failure in node lib

### ISSUE THREAD

**Issue by efrazier** [mscdex/node-mariasql#97]
I have been wanting to move a bunch of queries into a lib to start cleaning up some app code that has started to get complex and hard to read.  I might well have some generic JS issue here, but I can't see what it is or understand why I am getting no connection errors. They only clue I have is that if I print out the Mariasql object, I see this: 

sql  { threadId: undefined,
  connected: false,
  connecting: false,
  destroyed: false,
  pingInterval: 60000,
  _connecting: true,
  _destroying: false,
  _keepQueries: undefined,
  _pinger: undefined,
....

_connecting:true.... It seems like something is interuppting the connect and that leads to no error report. I did try hard coding the connect values with no change.  The DB is up and running of course(is it plugged in :) ) and other apps can connect using MariaSQL. It is also a MariaSQL server:

Server version: 10.1.2-MariaDB-1~trusty-wsrep-log mariadb.org binary distribution, wsrep_25.10.r4123

I also tried debug and single steping through the code, but I don't see any errors that way either. 

Any thoughts or "look here dummy" comments greatly appreciated. 

Thanks,

Eric 

-----------
dbInit.js
-----------

```javascript
var config = require('config');
var inspect = require('util').inspect;
var sql = require('mariasql');

var dbQuery = function () {};

    dbQuery.prototype.log = function () {
      console.log('dbQuery!');
    };


dbQuery.prototype.init = function () {
   if ( !process.env.SERVER_ENV ) {
   console.log("Missing SERVER_ENV SERVER_ENV=env-name node service.js ");
   process.exit(1);
   }

   var apiConfig = config.get('apiConfig');

   if (!apiConfig[process.env.SERVER_ENV] ){
     console.log("Missing SERVER_ENV or not in config SERVER_ENV=env-name node service.js ");
     process.exit(1);
   }

   var myConfig = apiConfig[process.env.SERVER_ENV]; // now my custom config
   console.log("My Config ",myConfig);

   var c = new sql();
   c.connect({
     host: myConfig.dbConfig['host'],
     user: myConfig.dbConfig['user'],
     password: myConfig.dbConfig['pass'],
     db: myConfig.dbConfig['db'],
     connTimeout: 60
   });


 

   c.on('connect', function() {
     console.log('Client connected');
   })
   .on('error', function(err) {
     console.log('Client error: ' + err);
   })
   .on('close', function(hadError) {
     console.log('Client closed');
   });

   global.vars = {updated:false,value:[],List: []};

   c.query('select Idx, Name FROM table where rs_id="main"')
    .on('result', function(res) {
      res.on('row', function(row) {
        console.log("row");
        global.evars.value[row.Idx] = (row.Name);
      })
      .on('error', function(err) {
        console.log('Result error: ' + inspect(err));
      })
      .on('end', function(info) {
        console.log('Result finished successfully');
      });
    })
    .on('end', function() {
      console.log('Done with all results vars');
      global.evars.updated=true;
      c.emit("DONE");
    });
console.log("sql ",c,global.vars);

dbQuery.prototype.sqlConnection = c;
dbQuery.prototype.config = myConfig;

}

exports.dbQuery = dbQuery;
```

------------
In the Main app:

```javascript
var qfd = require('./dbInit.js').dbQuery;

var dbQuery = new qfd;
dbQuery.log();
dbQuery.init();
```

**Comment by mscdex** [comment]
Can you please try the [rewrite](https://github.com/mscdex/node-mariasql/tree/rewrite) branch and let me know if you still encounter problems?

**Comment by efrazier** [comment]
I can't seem to find a way to install just via that branch.  It seems like I should be able to use something like npm rebuld, but not finding the way that works yet.  Thanks.

**Comment by mscdex** [comment]
You can use tarball urls with npm: `npm install https://github.com/mscdex/node-mariasql/tarball/rewrite`

**Comment by efrazier** [comment]
I did git clone and then cd into the node-mariasql dir and got this: 

eric@dev:node_modules$ git clone https://github.com/mscdex/node-mariasql.git
Cloning into 'node-mariasql'...
remote: Counting objects: 2171, done.
remote: Total 2171 (delta 0), reused 0 (delta 0), pack-reused 2171
Receiving objects: 100% (2171/2171), 6.05 MiB | 0 bytes/s, done.
Resolving deltas: 100% (875/875), done.
Checking connectivity... done.
eric@dev:node_modules$ cd node-mariasql/
eric@dev:node-mariasql$ npm install
\
> mariasql@0.1.23 install /home/eric/dbstuff/serviceAPI/node_modules/node-mariasql
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn ENOMEM
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at ChildProcess.spawn (child_process.js:948:11)
gyp ERR! stack     at Object.exports.spawn (child_process.js:736:9)
gyp ERR! stack     at Gyp.spawn (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:186:26)
gyp ERR! stack     at runGyp (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:333:18)
gyp ERR! stack     at findConfigs (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:247:23)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:253:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eric/dbstuff/serviceAPI/node_modules/node-mariasql
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>

npm ERR! mariasql@0.1.23 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the mariasql@0.1.23 install script.
npm ERR! This is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/eric/dbstuff/serviceAPI/node_modules/node-mariasql
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/eric/dbstuff/serviceAPI/node_modules/node-mariasql/npm-debug.log
npm ERR! not ok code 0

**Comment by efrazier** [comment]
Sorry just missed your comment: 

eric@dev:node_modules$ npm install https://github.com/mscdex/node-mariasql/tarball/rewrite
npm WARN package.json serviceAPI@1.0.0 No README data
FATAL ERROR: Evacuation Allocation failed - process out of memory
Aborted

This is only a 1G EC2 instance, but I wouldn't expect to actually need more memory for this path of install.

**Comment by mscdex** [comment]
I'm not familiar enough with EC2, but it installs fine on my Linux box with node v0.10 installed. Maybe something else on your system is using up too much memory and/or there is no swap configured? I don't know...

**Comment by efrazier** [comment]
It was really a lack of memory, got it building now after shuting down MySQL :) Will report back on results
