### ISSUE TITLE
npm install mariasql failes on Trusty Tahr

### ISSUE THREAD

**Issue by si-mikey** [mscdex/node-mariasql#98]
get this error when i try 'npm install mariasql'

> mariasql@0.1.23 install /home/mikey/code/nodejs/vroom/node_modules/mariasql
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/mikey/.nvm/v0.10.39/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "node" "/home/mikey/.nvm/v0.10.39/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mikey/code/nodejs/vroom/node_modules/mariasql
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! mariasql@0.1.23 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mariasql@0.1.23 install script.
npm ERR! This is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-55-generic
npm ERR! command "/home/mikey/.nvm/v0.10.39/bin/node" "/home/mikey/.nvm/v0.10.39/bin/npm" "install" "mariasql"
npm ERR! cwd /home/mikey/code/nodejs/vroom
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by mscdex** [comment]
My guess is that you have `gyp` installed from a repository. Uninstall that (`sudo apt-get remove gyp`) and it should work.
